[package]
name = "catena"
version = "0.1.0"
edition = "2024"

[dependencies]
hecs = "0.10"
nutype = { version = "0.7", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }

[dev-dependencies]
kani-verifier = "0.58"
proptest = "1"
serde_json = "1"
